import Head from "next/head";
import { useRouter } from "next/router";
import AdsBanner from "../components/AdsBanner";
import CAdsense from "../components/CAdsense";
import styles from "../styles/Home.module.css";

export default function Home() {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CAdsense />
      <button onClick={() => router.push("/coba")}>coba</button>
      <br />
      <button onClick={() => router.push("/test")}>Test</button>
    </div>
  );
}
